# This is a WIP to deploy infrastructure automatically
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    commands:
      - pip3 install -r requirements.txt
      - pip3 install -e awsutils
  build:
    commands:
      - ls
